Update c-cpp.yml
update workflow

diff --git a/.github/workflows/c-cpp.yml b/.github/workflows/c-cpp.yml
--- a/.github/workflows/c-cpp.yml
+++ b/.github/workflows/c-cpp.yml
@@ -2,25 +2,28 @@ name: C/C++ CI
 
 on:
   push:
-    branches: [ "main" ]
+    branches: [ "main", "master" ]
   pull_request:
-    branches: [ "main" ]
+    branches: [ "main", "master" ]
 
 jobs:
   build:
     runs-on: ubuntu-latest
 
     steps:
-      - uses: actions/checkout@v4
-      - name: Install autoconf (if required to generate configure)
-        run: sudo apt-get update && sudo apt-get install -y autoconf
-      - name: Generate configure (if missing)
-        run: autoreconf -i
-      - name: configure
-        run: ./configure
-      - name: make
-        run: make
-      - name: make check
-        run: make check
-      - name: make distcheck
-        run: make distcheck
+    - uses: actions/checkout@v3
+    
+    - name: Install dependencies
+      run: |
+        sudo apt-get update
+        sudo apt-get install -y g++ make
+        
+    - name: Build
+      run: make
+      
+    - name: Check executable
+      run: |
+        if [ ! -f "memory_game" ]; then
+          echo "Executable 'memory_game' not found!"
+          exit 1
+        fi
